DROP TABLE IF EXISTS COMMON_CODE;
DROP TABLE IF EXISTS DEVICE;
DROP TABLE IF EXISTS DEVICE_HISTORY;
DROP TABLE IF EXISTS DEVICE_TEMP;
DROP TABLE IF EXISTS ORGANIZATION;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS NOTICE;

CREATE TABLE COMMON_CODE
(
  CATEGORY      VARCHAR(10)  NULL     COMMENT '그룹 코드',
  CATEGORY_NAME VARCHAR(50)  NULL     COMMENT '그룹 명',
  CODE          VARCHAR(10)  NOT NULL COMMENT '코드',
  CODE_NAME     VARCHAR(100) NOT NULL COMMENT '코드명',
  USE_YN        CHAR(1)      NOT NULL DEFAULT 'Y' COMMENT '코드 사용 여부 (사용:Y, 미사용:N)'
);

CREATE TABLE DEVICE
(
  DEVICE_NUM        INT          NOT NULL AUTO_INCREMENT COMMENT '장비 순번',
  OLD_DEVICE_ID     VARCHAR(20)  NULL     COMMENT '기존 장비 관리 번호',
  EMP_NUM           INT          NULL     COMMENT '사원 번호',
  USAGE_DIVISION    VARCHAR(2)  NULL COMMENT '용도구분(업무용,개발용,실증용)',
  USAGE_PURPOSE     VARCHAR(100) NULL COMMENT '사용용도(개발업무용,내부망,외부망)',
  ARCHIVE_LOCATION  VARCHAR(200) NULL     COMMENT '사용/보관 위치',
  DEVICE_TYPE       VARCHAR(10)  NOT NULL COMMENT '장비 유형 코드',
  MANUFACTURER_CODE VARCHAR(10)  NULL     COMMENT '제조사 코드',
  MODEL_NAME        VARCHAR(100) NULL     COMMENT '모델명',
  MANUFACTURE_DATE  VARCHAR(8)   NULL     COMMENT '제조일자',
  CPU_SPEC          VARCHAR(100) NULL     COMMENT 'CPU 사양 (PC 전용)',
  MEMORY_SIZE       INT          NULL     COMMENT '메모리(GB, PC 전용)',
  STORAGE_INFO      VARCHAR(50)  NULL     COMMENT '스토리지 정보 (PC 전용)',
  OPERATING_SYSTEM  VARCHAR(100) NULL     COMMENT '운영체제',
  SCREEN_SIZE       DECIMAL(4,1) NULL     COMMENT '화면 크기 (PC/모니터 전용)',
  GPU_SPEC          VARCHAR(100) NULL     COMMENT 'GPU',
  DEVICE_STATUS_CODE       VARCHAR(2)  NULL     COMMENT '장비 상태 코드',
  APPROVAL_STATUS_CODE       VARCHAR(2)  NULL     COMMENT '결재 상태 코드',
  PURCHASE_DATE     VARCHAR(8)   NULL     COMMENT '구매일자',
  RETURN_DATE       VARCHAR(8)   NULL     COMMENT '반납일자',
  REMARKS           TEXT         NULL     COMMENT '비고',
  CREATE_DATETIME   DATETIME     NULL     DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  CREATE_USER       INT          NOT NULL COMMENT '생성자',
  UPDATE_DATETIME   DATETIME     NULL     DEFAULT CURRENT_TIMESTAMP COMMENT '최종 변경일시',
  UPDATE_USER       INT          NULL     COMMENT '최종 변경자',
  PRIMARY KEY (DEVICE_NUM)
);

CREATE TABLE asset_manager.DEVICE_HISTORY
(
  HISTORY_NUM       INT          NOT NULL AUTO_INCREMENT COMMENT '이력 순번',
  DEVICE_NUM        INT          NOT NULL COMMENT '장비 순번',
  EMP_NUM           INT          NULL     COMMENT '사원 번호',
  DEVICE_STATUS_CODE       VARCHAR(2)  NULL     COMMENT '장비 상태 코드',
  APPROVAL_STATUS_CODE       VARCHAR(2)  NULL     COMMENT '결재 상태 코드',
  CHANGE_CONTENTS     VARCHAR(2000)         NULL     COMMENT '변경내용',
  REASON     VARCHAR(1000)         NULL     COMMENT '사유',
  CREATE_DATETIME   DATETIME     NULL     DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  CREATE_USER       INT          NOT NULL COMMENT '생성자',
  PRIMARY KEY (HISTORY_NUM)
);

CREATE TABLE DEVICE_TEMP
(
  DEVICE_NUM        INT          NOT NULL COMMENT '장비 순번',
  OLD_DEVICE_ID     VARCHAR(20)  NULL     COMMENT '기존 장비 관리 번호',
  EMP_NUM           INT          NULL     COMMENT '사원 번호',
  USAGE_DIVISION    VARCHAR(2)  NULL COMMENT '용도구분(업무용,개발용,실증용)',
  USAGE_PURPOSE     VARCHAR(100) NULL COMMENT '사용용도(개발업무용,내부망,외부망)',
  ARCHIVE_LOCATION  VARCHAR(200) NULL     COMMENT '사용/보관 위치',
  DEVICE_TYPE       VARCHAR(10)  NOT NULL COMMENT '장비 유형 코드',
  MANUFACTURER_CODE VARCHAR(10)  NULL     COMMENT '제조사 코드',
  MODEL_NAME        VARCHAR(100) NULL     COMMENT '모델명',
  MANUFACTURE_DATE  VARCHAR(8)   NULL     COMMENT '제조일자',
  CPU_SPEC          VARCHAR(100) NULL     COMMENT 'CPU 사양 (PC 전용)',
  MEMORY_SIZE       INT          NULL     COMMENT '메모리(GB, PC 전용)',
  STORAGE_INFO      VARCHAR(50)  NULL     COMMENT '스토리지 정보 (PC 전용)',
  OPERATING_SYSTEM  VARCHAR(100) NULL     COMMENT '운영체제',
  SCREEN_SIZE       DECIMAL(4,1) NULL     COMMENT '화면 크기 (PC/모니터 전용)',
  GPU_SPEC          VARCHAR(100) NULL     COMMENT 'GPU',
  DEVICE_STATUS_CODE       VARCHAR(2)  NULL     COMMENT '장비 상태 코드',
  APPROVAL_STATUS_CODE       VARCHAR(2)  NULL     COMMENT '결재 상태 코드',
  PURCHASE_DATE     VARCHAR(8)   NULL     COMMENT '구매일자',
  RETURN_DATE       VARCHAR(8)   NULL     COMMENT '반납일자',
  REMARKS           TEXT         NULL     COMMENT '비고',
  CHANGE_REASON     TEXT         NULL     COMMENT '변경사유'
);

CREATE TABLE NOTICE
(
  NOTICE_NUM      INT          NOT NULL AUTO_INCREMENT COMMENT '공지사항 번호',
  TITLE           VARCHAR(255) NOT NULL COMMENT '제목',
  CONTENT         TEXT         NOT NULL COMMENT '본문 내용',
  CREATE_DATETIME DATETIME     NULL     DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  CREATE_USER     INT          NOT NULL COMMENT '생성자',
  UPDATE_DATETIME DATETIME     NULL     DEFAULT CURRENT_TIMESTAMP COMMENT '최종 변경일시',
  UPDATE_USER     INT          NULL     COMMENT '최종 변경자',
  PRIMARY KEY (NOTICE_NUM)
);

CREATE TABLE ORGANIZATION
(
  ORG_ID          INT                                  NOT NULL COMMENT '조직 ID (기본키)',
  ORG_NAME        	VARCHAR(100)                       NOT NULL COMMENT '조직명',
  ORG_TYPE        ENUM('COMPANY', 'DIVISION', 'TEAM')  NOT NULL COMMENT '조직 유형 (COMPANY:회사, DIVISION:본부, TEAM:팀)',
  PARENT_ORG_ID   INT                                  NULL     DEFAULT 1 COMMENT '상위 조직 ID (자기 참조, 최상위는 NULL)',
  ORG_LEVEL       INT                                  NULL     COMMENT '조직 레벨 (1:회사, 2:본부, 3:팀)',
  ORG_PATH        VARCHAR(20)                          NULL     COMMENT '조직 경로 (1/2/3/4 형태로 계층 구조 표현)',
  SORT_ORDER      INT                                  NULL     DEFAULT 0 COMMENT '정렬 순서 (같은 레벨 내에서의 표시 순서)',
  IS_ACTIVE       CHAR(1)                              NULL     COMMENT '활성 여부 (Y:활성, N:비활성)',
  CREATE_DATETIME DATETIME                             NULL     DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ORG_ID)
) COMMENT '조직 정보 통합 테이블 (회사, 본부, 팀 계층 구조 관리)';

CREATE TABLE USER
(
  EMP_NUM              INT          NOT NULL COMMENT '사원 번호',
  USER_ID              VARCHAR(50)  NOT NULL COMMENT '사용자 ID (회사 메일 계정)',
  USER_NAME            VARCHAR(100) NOT NULL COMMENT '사용자명',
  PASSWORD             VARCHAR(100) NULL     DEFAULT '0ffe1abd1a08215353c233d6e009613e95eec4253832a761af28ff37ac5a150c' COMMENT '비밀번호 (암호화 SHA256)',
  ORG_ID               INT          NOT NULL COMMENT '조직 ID (기본키)',
  USER_POSITION_CD     VARCHAR(10)  NULL     COMMENT '직책 코드',
  USER_GRADE_CD        VARCHAR(10)  NOT NULL COMMENT '직위 코드',
  ROLE_CODE            VARCHAR(10)  NOT NULL COMMENT '권한 코드 (COMMON_CODE)',
  IS_EMPLOYED          CHAR(1)      NOT NULL DEFAULT 'Y' COMMENT '재직여부 (재직중:Y, 퇴사:N)',
  PASSWORD_CHANGE_DATE VARCHAR(8)   NULL     COMMENT '비밀번호 변경일자',
  PASSWORD_RESET_REQ   CHAR         NULL     DEFAULT 'N' COMMENT '비밀번호 초기화 요청(초기화요청:Y, 미요청:N)',
  CREATE_DATETIME      DATETIME     NULL     DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  PRIMARY KEY (EMP_NUM)
);

/******** INSERT DATA ********/
/* ORGANIZATION */
INSERT INTO ORGANIZATION (ORG_ID, ORG_NAME, ORG_TYPE, PARENT_ORG_ID, ORG_LEVEL, ORG_PATH, SORT_ORDER, IS_ACTIVE, CREATE_DATETIME) VALUES 
(1, '지어소프트', 'COMPANY', NULL, 1, '1', 1, 'Y', NOW()),
(12, 'IT서비스부문', 'DIVISION', 1, 2, '1/2', 1, 'Y', NOW()),
(121, '지능형플랫폼사업팀', 'TEAM', 12, 3, '1/2/3', 1, 'Y', NOW()),
(122, '전략사업팀', 'TEAM', 12, 3, '1/2/3', 2, 'Y', NOW()),
(123, 'D-Inno 개발팀', 'TEAM', 12, 3, '1/2/3', 3, 'Y', NOW()),
(124, '플랫폼개발팀', 'TEAM', 12, 3, '1/2/3', 4, 'Y', NOW()),
(125, '오픈서비스사업팀', 'TEAM', 12, 3, '1/2/3', 5, 'Y', NOW()),
(126, '비즈니스 기술연구소', 'TEAM', 12, 3, '1/2/3', 6, 'Y', NOW()),
(127, 'SD본부', 'TEAM', 12, 3, '1/2/3', 7, 'Y', NOW());

INSERT INTO ORGANIZATION (ORG_ID, ORG_NAME, ORG_TYPE, PARENT_ORG_ID, ORG_LEVEL, ORG_PATH, SORT_ORDER, IS_ACTIVE, CREATE_DATETIME) VALUES 
(13, '광고사업부문', 'DIVISION', 1, 2, '1/2', 3, 'Y', NOW()),
(14, '이커머스부문', 'DIVISION', 1, 2, '1/2', 4, 'Y', NOW()),
(15, '솔루션사업부', 'DIVISION', 1, 2, '1/2', 5, 'Y', NOW());

INSERT INTO ORGANIZATION (ORG_ID, ORG_NAME, ORG_TYPE, PARENT_ORG_ID, ORG_LEVEL, ORG_PATH, SORT_ORDER, IS_ACTIVE, CREATE_DATETIME) VALUES 
(2, '오아시스', 'COMPANY', NULL, 1, '1', 2, 'Y', NOW());

/* COMMON_CODE */
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('C001', '직책', '03', '팀장', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('C001', '직책', '04', '팀원', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('C002', '직위', '03', '부장', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('C002', '직위', '04', '차장', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('C002', '직위', '05', '과장', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('C002', '직위', '06', '대리', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('C002', '직위', '07', '사원', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('C003', '권한', '00', 'User', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('C003', '권한', '01', 'Team-manager', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('C003', '권한', '02', 'Asset-manager', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('C003', '권한', '03', 'System-manager', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('C004', '장비유형코드', 'PC', '컴퓨터', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('C004', '장비유형코드', 'MO', '모니터', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('C004', '장비유형코드', 'HP', '핸드폰', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('C004', '장비유형코드', 'ETC', '기타', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('C005', '장비상태코드', '01', '대기', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('C005', '장비상태코드', '02', '사용', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('C005', '장비상태코드', '03', '반납', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('C005', '장비상태코드', '04', '파손', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('C005', '장비상태코드', '05', '폐기', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('C006', '결재상태코드', 'A1', '부서장 승인대기', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('C006', '결재상태코드', 'A2', '관리자 승인대기', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('C006', '결재상태코드', 'A3', '승인완료', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('C006', '결재상태코드', 'A4', '반려', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('C007', '용도구분', '01', '업무용', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('C007', '용도구분', '02', '개발용', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('C007', '용도구분', '03', '실증용', 'Y');


/* NOTICE */
INSERT INTO NOTICE (TITLE, CONTENT, CREATE_DATETIME, CREATE_USER, UPDATE_DATETIME, UPDATE_USER) VALUES ('공지사항', 'IT서비스부문 공지사항입니다.', NOW(), 100000, NOW(), 100000);
INSERT INTO NOTICE (TITLE, CONTENT, CREATE_DATETIME, CREATE_USER, UPDATE_DATETIME, UPDATE_USER) VALUES ('공지사항', '오픈서비스사업팀 공지사항입니다.', NOW(), 100008, NOW(), 100000);

/* DEVICE */
INSERT INTO DEVICE(OLD_DEVICE_ID, EMP_NUM, USAGE_DIVISION, USAGE_PURPOSE, ARCHIVE_LOCATION, DEVICE_TYPE, MANUFACTURER_CODE, MODEL_NAME, MANUFACTURE_DATE, CPU_SPEC, MEMORY_SIZE, STORAGE_INFO, OPERATING_SYSTEM, SCREEN_SIZE, GPU_SPEC, DEVICE_STATUS_CODE, APPROVAL_STATUS_CODE, PURCHASE_DATE, RETURN_DATE, REMARKS, CREATE_DATETIME, CREATE_USER, UPDATE_DATETIME, UPDATE_USER)VALUES('IT-PC-000592', 100001, '01', '개발업무용', '선릉 패스트파이브', 'PC', 'LG', '15Z90S-GP56ML', '2024', 'Ultra5 125H', 16, '256', '11/64', 15, '', '02', '','20240101', '', '', NOW(), 100000, NOW(), 100000);
INSERT INTO DEVICE(OLD_DEVICE_ID, EMP_NUM, USAGE_DIVISION, USAGE_PURPOSE, ARCHIVE_LOCATION, DEVICE_TYPE, MANUFACTURER_CODE, MODEL_NAME, MANUFACTURE_DATE, CPU_SPEC, MEMORY_SIZE, STORAGE_INFO, OPERATING_SYSTEM, SCREEN_SIZE, GPU_SPEC, DEVICE_STATUS_CODE, APPROVAL_STATUS_CODE, PURCHASE_DATE, RETURN_DATE, REMARKS, CREATE_DATETIME, CREATE_USER, UPDATE_DATETIME, UPDATE_USER)VALUES('IT-PC-000589', 100002, '01', '개발업무용', '선릉 패스트파이브', 'PC', 'LG', '15Z90S-GP56ML', '2024', 'Ultra5 125H', 16, '256', '11/64', 15, '', '02', '', '20240101', '', '', NOW(), 100000, NOW(), 100000);
INSERT INTO DEVICE(OLD_DEVICE_ID, EMP_NUM, USAGE_DIVISION, USAGE_PURPOSE, ARCHIVE_LOCATION, DEVICE_TYPE, MANUFACTURER_CODE, MODEL_NAME, MANUFACTURE_DATE, CPU_SPEC, MEMORY_SIZE, STORAGE_INFO, OPERATING_SYSTEM, SCREEN_SIZE, GPU_SPEC, DEVICE_STATUS_CODE, APPROVAL_STATUS_CODE, PURCHASE_DATE, RETURN_DATE, REMARKS, CREATE_DATETIME, CREATE_USER, UPDATE_DATETIME, UPDATE_USER)VALUES('IT-PC-000589', 100009, '02', '개발업무용', '신세계푸드 본사', 'PC', '삼성', 'NT500R5S', '2016', 'i5-5200U', 8, '128/750', '10/64', 15, '', '03', '', '20160101', '', '신세계푸드 원격 접속용 반출 PC', NOW(), 100000, NOW(), 100000);

/* USER */
INSERT INTO USER(EMP_NUM, USER_ID, USER_NAME, ORG_ID, USER_POSITION_CD, USER_GRADE_CD, ROLE_CODE, IS_EMPLOYED, PASSWORD_CHANGE_DATE, CREATE_DATETIME)VALUES
(100000, 'dhlee', '이대현', 125, '03', '03', '01', 'Y', '', NOW()),
(100001, 'nile', '이한나', 125, '04', '07', '00', 'Y', '', NOW()),
(100002, 'hwheo', '허희원', 125, '04', '07', '00', 'Y', '', NOW()),
(100003, 'hsjeong', '정화수', 125, '04', '04', '00', 'Y', '', NOW()),
(100004, 'isac9305', '신이삭', 125, '04', '06', '00', 'Y', '', NOW()),
(100005, 'waterather21', '김우진', 125, '04', '06', '00', 'Y', '', NOW()),
(100006, 'lyj', '이윤주', 125, '04', '07', '00', 'Y', '', NOW()),
(100007, 'hys', '한유성', 125, '04', '03', '02', 'Y', '', NOW()),
(100008, 'ksyang7', '양승은', 125, '04', '03', '03', 'Y', '', NOW()),
(100009, 'hslee', '이효성', 125, '04', '04', '00', 'Y', '', NOW()),
(100010, 'cglee', '이창구', 125, '04', '04', '00', 'Y', '', NOW()),
(100011, 'ydshim', '심영도', 125, '04', '06', '00', 'Y', '', NOW());

INSERT INTO DEVICE_HISTORY (
  HISTORY_NUM, DEVICE_NUM, EMP_NUM, DEVICE_STATUS_CODE, APPROVAL_STATUS_CODE,
  CHANGE_CONTENTS, REASON, CREATE_DATETIME, CREATE_USER
) VALUES
(1, 1, 100007, '01', 'A1', '장비 상태 초기화', '일정 점검 후 초기화', NOW(), 100000),
(2, 2, 100007, '02', 'A2', '장비 상태 변경됨', '오류 발생으로 인한 조치', NOW(), 100000),
(3, 3, 100007, '03', 'A3', '승인 상태 변경', '관리자 요청', NOW(), 100000),
(4, 1, 100007, '02', 'A1', '장비 재활성화', '유지보수 완료', NOW(), 100000),
(5, 2, 100007, '01', 'A3', '상태 초기화 및 승인', '긴급 상황 대응', NOW(), 100000),
(6, 3, 100007, '03', 'A2', '장비 상태 종료', '계획된 종료', NOW(), 100000),
(7, 1, 100007, '01', 'A1', '기본 상태로 설정', '신규 등록 후 설정', NOW(), 100000),
(8, 2, 100007, '02', 'A2', '장비 테스트 완료', '테스트 후 반영', NOW(), 100000),
(9, 3, 100007, '03', 'A3', '장비 상태 자동 업데이트', '시스템 자동 반영', NOW(), 100000),
(10, 1, 100007, '02', 'A1', '재부팅 후 정상 작동', '사용자 요청', NOW(), 100000);
