DROP TABLE IF EXISTS COMMON_CODE;
DROP TABLE IF EXISTS DEVICE;
DROP TABLE IF EXISTS DEVICE_HISTORY;
DROP TABLE IF EXISTS DEVICE_TEMP;
DROP TABLE IF EXISTS ORGANIZATION;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS NOTICE;

CREATE TABLE COMMON_CODE
(
  CATEGORY      VARCHAR(10)  NULL     COMMENT '그룹 코드',
  CATEGORY_NAME VARCHAR(50)  NULL     COMMENT '그룹 명',
  CODE          VARCHAR(10)  NOT NULL COMMENT '코드',
  CODE_NAME     VARCHAR(100) NOT NULL COMMENT '코드명',
  USE_YN        CHAR(1)      NOT NULL DEFAULT 'Y' COMMENT '코드 사용 여부 (사용:Y, 미사용:N)'
);

CREATE TABLE DEVICE
(
  DEVICE_NUM        INT          NOT NULL AUTO_INCREMENT COMMENT '장비 순번',
  OLD_DEVICE_ID     VARCHAR(20)  NULL     COMMENT '기존 장비 관리 번호',
  EMP_NUM           INT          NULL     COMMENT '사원 번호',
  ORG_ID            INT          NOT NULL COMMENT '조직 ID (기본키)',
  USAGE_DIVISION    VARCHAR(10)  NOT NULL COMMENT '용도구분(업무용,개발용,실증용)',
  USAGE_PURPOSE     VARCHAR(200) NOT NULL COMMENT '사용용도(개발업무용,내부망,외부망)',
  ARCHIVE_LOCATION  VARCHAR(200) NULL     COMMENT '사용/보관 위치',
  DEVICE_TYPE       VARCHAR(10)  NOT NULL COMMENT '장비 유형 코드',
  MANUFACTURER_CODE VARCHAR(10)  NULL     COMMENT '제조사 코드',
  MODEL_NAME        VARCHAR(100) NULL     COMMENT '모델명',
  MANUFACTURE_DATE  VARCHAR(8)   NULL     COMMENT '제조일자',
  CPU_SPEC          VARCHAR(100) NULL     COMMENT 'CPU 사양 (PC 전용)',
  MEMORY_SIZE       INT          NULL     COMMENT '메모리(GB, PC 전용)',
  STORAGE_INFO      VARCHAR(50)  NULL     COMMENT '스토리지 정보 (PC 전용)',
  OPERATING_SYSTEM  VARCHAR(100) NULL     COMMENT '운영체제',
  SCREEN_SIZE       DECIMAL(4,1) NULL     COMMENT '화면 크기 (PC/모니터 전용)',
  GPU_SPEC          VARCHAR(100) NULL     COMMENT 'GPU',
  STATUS_CODE       VARCHAR(10)  NULL     COMMENT '장비 상태 코드',
  PURCHASE_DATE     VARCHAR(8)   NULL     COMMENT '구매일자',
  RETURN_DATE       VARCHAR(8)   NULL     COMMENT '반납일자',
  REMARKS           TEXT         NULL     COMMENT '비고',
  CREATE_DATETIME   DATETIME     NULL     DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  CREATE_USER       INT          NOT NULL COMMENT '생성자',
  UPDATE_DATETIME   DATETIME     NULL     DEFAULT CURRENT_TIMESTAMP COMMENT '최종 변경일시',
  UPDATE_USER       INT          NULL     COMMENT '최종 변경자',
  PRIMARY KEY (DEVICE_NUM)
);

CREATE TABLE DEVICE_HISTORY
(
  HISTORY_NUM       INT          NOT NULL COMMENT '이력 순번',
  DEVICE_NUM        INT          NOT NULL COMMENT '장비 순번',
  OLD_DEVICE_ID     VARCHAR(20)  NULL     COMMENT '기존 장비 관리 번호',
  EMP_NUM           INT          NULL     COMMENT '사원 번호',
  ORG_ID            INT          NOT NULL COMMENT '조직 ID (기본키)',
  USAGE_DIVISION    VARCHAR(10)  NOT NULL COMMENT '용도구분(업무용,개발용,실증용)',
  USAGE_PURPOSE     VARCHAR(200) NOT NULL COMMENT '사용용도(개발업무용,내부망,외부망)',
  ARCHIVE_LOCATION  VARCHAR(200) NULL     COMMENT '사용/보관 위치',
  DEVICE_TYPE       VARCHAR(10)  NOT NULL COMMENT '장비 유형 코드',
  MANUFACTURER_CODE VARCHAR(10)  NULL     COMMENT '제조사 코드',
  MODEL_NAME        VARCHAR(100) NULL     COMMENT '모델명',
  MANUFACTURE_DATE  VARCHAR(8)   NULL     COMMENT '제조일자',
  CPU_SPEC          VARCHAR(100) NULL     COMMENT 'CPU 사양 (PC 전용)',
  MEMORY_SIZE       INT          NULL     COMMENT '메모리(GB, PC 전용)',
  STORAGE_INFO      VARCHAR(50)  NULL     COMMENT '스토리지 정보 (PC 전용)',
  OPERATING_SYSTEM  VARCHAR(100) NULL     COMMENT '운영체제',
  SCREEN_SIZE       DECIMAL(4,1) NULL     COMMENT '화면 크기 (PC/모니터 전용)',
  GPU_SPEC          VARCHAR(100) NULL     COMMENT 'GPU',
  STATUS_CODE       VARCHAR(10)  NULL     COMMENT '장비 상태 코드',
  PURCHASE_DATE     VARCHAR(8)   NULL     COMMENT '구매일자',
  RETURN_DATE       VARCHAR(8)   NULL     COMMENT '반납일자',
  REMARKS           TEXT         NULL     COMMENT '비고',
  CHANGE_REASON     TEXT         NULL     COMMENT '변경사유',
  CREATE_DATETIME   DATETIME     NULL     DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  CREATE_USER       INT          NOT NULL COMMENT '생성자',
  PRIMARY KEY (HISTORY_NUM)
);

CREATE TABLE DEVICE_TEMP
(
  DEVICE_NUM        INT          NOT NULL COMMENT '장비 순번',
  OLD_DEVICE_ID     VARCHAR(20)  NULL     COMMENT '기존 장비 관리 번호',
  EMP_NUM           INT          NULL     COMMENT '사원 번호',
  ORG_ID            INT          NOT NULL COMMENT '조직 ID (기본키)',
  USAGE_DIVISION    VARCHAR(10)  NOT NULL COMMENT '용도구분(업무용,개발용,실증용)',
  USAGE_PURPOSE     VARCHAR(200) NOT NULL COMMENT '사용용도(개발업무용,내부망,외부망)',
  ARCHIVE_LOCATION  VARCHAR(200) NULL     COMMENT '사용/보관 위치',
  DEVICE_TYPE       VARCHAR(10)  NOT NULL COMMENT '장비 유형 코드',
  MANUFACTURER_CODE VARCHAR(10)  NULL     COMMENT '제조사 코드',
  MODEL_NAME        VARCHAR(100) NULL     COMMENT '모델명',
  MANUFACTURE_DATE  VARCHAR(8)   NULL     COMMENT '제조일자',
  CPU_SPEC          VARCHAR(100) NULL     COMMENT 'CPU 사양 (PC 전용)',
  MEMORY_SIZE       INT          NULL     COMMENT '메모리(GB, PC 전용)',
  STORAGE_INFO      VARCHAR(50)  NULL     COMMENT '스토리지 정보 (PC 전용)',
  OPERATING_SYSTEM  VARCHAR(100) NULL     COMMENT '운영체제',
  SCREEN_SIZE       DECIMAL(4,1) NULL     COMMENT '화면 크기 (PC/모니터 전용)',
  GPU_SPEC          VARCHAR(100) NULL     COMMENT 'GPU',
  STATUS_CODE       VARCHAR(10)  NULL     COMMENT '장비 상태 코드',
  PURCHASE_DATE     VARCHAR(8)   NULL     COMMENT '구매일자',
  RETURN_DATE       VARCHAR(8)   NULL     COMMENT '반납일자',
  REMARKS           TEXT         NULL     COMMENT '비고',
  CHANGE_REASON     TEXT         NULL     COMMENT '변경사유'
);

CREATE TABLE NOTICE
(
  NOTICE_NUM      INT          NOT NULL AUTO_INCREMENT COMMENT '공지사항 번호',
  TITLE           VARCHAR(255) NOT NULL COMMENT '제목',
  CONTENT         TEXT         NOT NULL COMMENT '본문 내용',
  CREATE_DATETIME DATETIME     NULL     DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  CREATE_USER     INT          NOT NULL COMMENT '생성자',
  UPDATE_DATETIME DATETIME     NULL     DEFAULT CURRENT_TIMESTAMP COMMENT '최종 변경일시',
  UPDATE_USER     INT          NULL     COMMENT '최종 변경자',
  PRIMARY KEY (NOTICE_NUM)
);

CREATE TABLE ORGANIZATION
(
  ORG_ID          INT                                  NOT NULL COMMENT '조직 ID (기본키)',
  ORG_NAME        	VARCHAR(100)                       NOT NULL COMMENT '조직명',
  ORG_TYPE        ENUM('COMPANY', 'DIVISION', 'TEAM')  NOT NULL COMMENT '조직 유형 (COMPANY:회사, DIVISION:본부, TEAM:팀)',
  PARENT_ORG_ID   INT                                  NULL     DEFAULT 1 COMMENT '상위 조직 ID (자기 참조, 최상위는 NULL)',
  ORG_LEVEL       INT                                  NULL     COMMENT '조직 레벨 (1:회사, 2:본부, 3:팀)',
  ORG_PATH        VARCHAR(20)                          NULL     COMMENT '조직 경로 (1/2/3/4 형태로 계층 구조 표현)',
  SORT_ORDER      INT                                  NULL     DEFAULT 0 COMMENT '정렬 순서 (같은 레벨 내에서의 표시 순서)',
  IS_ACTIVE       CHAR(1)                              NULL     COMMENT '활성 여부 (Y:활성, N:비활성)',
  CREATE_DATETIME DATETIME                             NULL     DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ORG_ID)
) COMMENT '조직 정보 통합 테이블 (회사, 본부, 팀 계층 구조 관리)';

CREATE TABLE USER
(
  EMP_NUM              INT          NOT NULL COMMENT '사원 번호',
  USER_ID              VARCHAR(50)  NOT NULL COMMENT '사용자 ID (회사 메일 계정)',
  USER_NAME            VARCHAR(100) NOT NULL COMMENT '사용자명',
  PASSWORD             VARCHAR(100) NULL     DEFAULT '$2a$10$heD/fJX.YJNqkiHz2zidi.YSmhHGr5ELc0khX.93eU9rsuWQLI49i' COMMENT '비밀번호 (암호화 BCrypt)',
  ORG_ID               INT          NOT NULL COMMENT '조직 ID (기본키)',
  USER_POSITION_CD     VARCHAR(10)  NULL     COMMENT '직책 코드',
  USER_GRADE_CD        VARCHAR(10)  NOT NULL COMMENT '직위 코드',
  ROLE_CODE            VARCHAR(10)  NOT NULL COMMENT '권한 코드 (COMMON_CODE)',
  IS_EMPLOYED          CHAR(1)      NOT NULL DEFAULT 'Y' COMMENT '재직여부 (재직중:Y, 퇴사:N)',
  PASSWORD_CHANGE_DATE VARCHAR(8)   NULL     COMMENT '비밀번호 변경일자',
  CREATE_DATETIME      DATETIME     NULL     DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  PRIMARY KEY (EMP_NUM)
);






/******** INSERT DATA ********/
/* ORGANIZATION */
INSERT INTO ORGANIZATION (ORG_ID, ORG_NAME, ORG_TYPE, PARENT_ORG_ID, ORG_LEVEL, ORG_PATH, SORT_ORDER, IS_ACTIVE, CREATE_DATETIME) VALUES (1, '지어소프트', 'COMPANY', NULL, 1, '1', 1, 'Y', NOW());
INSERT INTO ORGANIZATION (ORG_ID, ORG_NAME, ORG_TYPE, PARENT_ORG_ID, ORG_LEVEL, ORG_PATH, SORT_ORDER, IS_ACTIVE, CREATE_DATETIME) VALUES (13, 'IT서비스부문', 'DIVISION', 1, 2, '1/2', 3, 'Y', NOW());
INSERT INTO ORGANIZATION (ORG_ID, ORG_NAME, ORG_TYPE, PARENT_ORG_ID, ORG_LEVEL, ORG_PATH, SORT_ORDER, IS_ACTIVE, CREATE_DATETIME) VALUES (135, '오픈서비스사업팀', 'TEAM', 3, 3, '1/2/3', 5, 'Y', NOW());

/* COMMON_CODE */
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('1', '직책', '03', '팀장', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('1', '직책', '04', '팀원', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('2', '직위', '03', '부장', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('2', '직위', '04', '과장', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('2', '직위', '05', '차장', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('2', '직위', '06', '대리', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('2', '직위', '07', '사원', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('3', '권한', '01', 'Team-manager', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('3', '권한', '02', 'Asset-manager', 'Y');
INSERT INTO COMMON_CODE (CATEGORY, CATEGORY_NAME, CODE, CODE_NAME, USE_YN) VALUES ('3', '권한', '03', 'System-manager', 'Y');

/* NOTICE */
INSERT INTO NOTICE (TITLE, CONTENT, CREATE_DATETIME, CREATE_USER, UPDATE_DATETIME, UPDATE_USER) VALUES ('공지사항', 'IT서비스부문 공지사항입니다.', NOW(), 100000, NOW(), 100000);
INSERT INTO NOTICE (TITLE, CONTENT, CREATE_DATETIME, CREATE_USER, UPDATE_DATETIME, UPDATE_USER) VALUES ('공지사항', '오픈서비스사업팀 공지사항입니다.', NOW(), 100008, NOW(), 100000);

/* DEVICE */
INSERT INTO DEVICE(OLD_DEVICE_ID, EMP_NUM, ORG_ID, USAGE_DIVISION, USAGE_PURPOSE, ARCHIVE_LOCATION, DEVICE_TYPE, MANUFACTURER_CODE, MODEL_NAME, MANUFACTURE_DATE, CPU_SPEC, MEMORY_SIZE, STORAGE_INFO, OPERATING_SYSTEM, SCREEN_SIZE, GPU_SPEC, STATUS_CODE, PURCHASE_DATE, RETURN_DATE, REMARKS, CREATE_DATETIME, CREATE_USER, UPDATE_DATETIME, UPDATE_USER)VALUES('IT-PC-000592', 100001, 135, '업무용', '개발업무용', '선릉 패스트파이브', '노트북', 'LG', '15Z90S-GP56ML', '2024', 'Ultra5 125H', 16, '256', '11/64', 15, '', '사용', '2024', '', '', NOW(), 100000, NOW(), 100000);
INSERT INTO DEVICE(OLD_DEVICE_ID, EMP_NUM, ORG_ID, USAGE_DIVISION, USAGE_PURPOSE, ARCHIVE_LOCATION, DEVICE_TYPE, MANUFACTURER_CODE, MODEL_NAME, MANUFACTURE_DATE, CPU_SPEC, MEMORY_SIZE, STORAGE_INFO, OPERATING_SYSTEM, SCREEN_SIZE, GPU_SPEC, STATUS_CODE, PURCHASE_DATE, RETURN_DATE, REMARKS, CREATE_DATETIME, CREATE_USER, UPDATE_DATETIME, UPDATE_USER)VALUES('IT-PC-000589', 100002, 135, '업무용', '개발업무용', '선릉 패스트파이브', '노트북', 'LG', '15Z90S-GP56ML', '2024', 'Ultra5 125H', 16, '256', '11/64', 15, '', '사용', '2024', '', '', NOW(), 100000, NOW(), 100000);
INSERT INTO DEVICE(OLD_DEVICE_ID, EMP_NUM, ORG_ID, USAGE_DIVISION, USAGE_PURPOSE, ARCHIVE_LOCATION, DEVICE_TYPE, MANUFACTURER_CODE, MODEL_NAME, MANUFACTURE_DATE, CPU_SPEC, MEMORY_SIZE, STORAGE_INFO, OPERATING_SYSTEM, SCREEN_SIZE, GPU_SPEC, STATUS_CODE, PURCHASE_DATE, RETURN_DATE, REMARKS, CREATE_DATETIME, CREATE_USER, UPDATE_DATETIME, UPDATE_USER)VALUES('IT-PC-000589', 100009, 135, '업무용', '개발업무용', '신세계푸드 본사', '노트북', '삼성', 'NT500R5S', '2016', 'i5-5200U', 8, '128/750', '10/64', 15, '', '사용', '2016', '', '신세계푸드 원격 접속용 반출 PC', NOW(), 100000, NOW(), 100000);

/* USER */
INSERT INTO USER(EMP_NUM, USER_ID, USER_NAME, ORG_ID, USER_POSITION_CD, USER_GRADE_CD, ROLE_CODE, IS_EMPLOYED, PASSWORD_CHANGE_DATE, CREATE_DATETIME)VALUES(100000, 'dhlee', '이대현', 135, '03', '03', '01', 'Y', '', NOW());
INSERT INTO USER(EMP_NUM, USER_ID, USER_NAME, ORG_ID, USER_POSITION_CD, USER_GRADE_CD, ROLE_CODE, IS_EMPLOYED, PASSWORD_CHANGE_DATE, CREATE_DATETIME)VALUES(100001, 'nile', '이한나', 135, '04', '07', '', 'Y', '', NOW());
INSERT INTO USER(EMP_NUM, USER_ID, USER_NAME, ORG_ID, USER_POSITION_CD, USER_GRADE_CD, ROLE_CODE, IS_EMPLOYED, PASSWORD_CHANGE_DATE, CREATE_DATETIME)VALUES(100002, 'hwheo', '허희원', 135, '04', '07', '', 'Y', '', NOW());
INSERT INTO USER(EMP_NUM, USER_ID, USER_NAME, ORG_ID, USER_POSITION_CD, USER_GRADE_CD, ROLE_CODE, IS_EMPLOYED, PASSWORD_CHANGE_DATE, CREATE_DATETIME)VALUES(100003, 'hsjeong', '정화수', 135, '04', '04', '', 'Y', '', NOW());
INSERT INTO USER(EMP_NUM, USER_ID, USER_NAME, ORG_ID, USER_POSITION_CD, USER_GRADE_CD, ROLE_CODE, IS_EMPLOYED, PASSWORD_CHANGE_DATE, CREATE_DATETIME)VALUES(100004, 'isac9305', '신이삭', 135, '04', '06', '', 'Y', '', NOW());
INSERT INTO USER(EMP_NUM, USER_ID, USER_NAME, ORG_ID, USER_POSITION_CD, USER_GRADE_CD, ROLE_CODE, IS_EMPLOYED, PASSWORD_CHANGE_DATE, CREATE_DATETIME)VALUES(100005, 'waterather21', '김우진', 135, '04', '06', '', 'Y', '', NOW());
INSERT INTO USER(EMP_NUM, USER_ID, USER_NAME, ORG_ID, USER_POSITION_CD, USER_GRADE_CD, ROLE_CODE, IS_EMPLOYED, PASSWORD_CHANGE_DATE, CREATE_DATETIME)VALUES(100006, 'lyj', '이윤주', 135, '04', '07', '', 'Y', '', NOW());
INSERT INTO USER(EMP_NUM, USER_ID, USER_NAME, ORG_ID, USER_POSITION_CD, USER_GRADE_CD, ROLE_CODE, IS_EMPLOYED, PASSWORD_CHANGE_DATE, CREATE_DATETIME)VALUES(100007, 'hys', '한유성', 135, '04', '03', '02', 'Y', '', NOW());
INSERT INTO USER(EMP_NUM, USER_ID, USER_NAME, ORG_ID, USER_POSITION_CD, USER_GRADE_CD, ROLE_CODE, IS_EMPLOYED, PASSWORD_CHANGE_DATE, CREATE_DATETIME)VALUES(100008, 'ksyang7', '양승은', 135, '04', '03', '03', 'Y', '', NOW());
INSERT INTO USER(EMP_NUM, USER_ID, USER_NAME, ORG_ID, USER_POSITION_CD, USER_GRADE_CD, ROLE_CODE, IS_EMPLOYED, PASSWORD_CHANGE_DATE, CREATE_DATETIME)VALUES(100009, 'hslee', '이효성', 135, '04', '04', '', 'Y', '', NOW());
INSERT INTO USER(EMP_NUM, USER_ID, USER_NAME, ORG_ID, USER_POSITION_CD, USER_GRADE_CD, ROLE_CODE, IS_EMPLOYED, PASSWORD_CHANGE_DATE, CREATE_DATETIME)VALUES(100010, 'cglee', '이창구', 135, '04', '04', '', 'Y', '', NOW());
INSERT INTO USER(EMP_NUM, USER_ID, USER_NAME, ORG_ID, USER_POSITION_CD, USER_GRADE_CD, ROLE_CODE, IS_EMPLOYED, PASSWORD_CHANGE_DATE, CREATE_DATETIME)VALUES(100011, 'ydshim', '심영도', 135, '04', '06', '', 'Y', '', NOW());