DROP TABLE IF EXISTS COMMON_CODE;
DROP TABLE IF EXISTS DEVICE;
DROP TABLE IF EXISTS DEVICE_HISTORY;
DROP TABLE IF EXISTS DEVICE_TEMP;
DROP TABLE IF EXISTS ORGANIZATION;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS NOTICE;

CREATE TABLE COMMON_CODE
(
  CATEGORY      VARCHAR(10)  NULL     COMMENT '그룹 코드',
  CATEGORY_NAME VARCHAR(50)  NULL     COMMENT '그룹 명',
  CODE          VARCHAR(10)  NOT NULL COMMENT '코드',
  CODE_NAME     VARCHAR(100) NOT NULL COMMENT '코드명',
  USE_YN        CHAR(1)      NOT NULL DEFAULT 'Y' COMMENT '코드 사용 여부 (사용:Y, 미사용:N)'
);

CREATE TABLE DEVICE
(
  DEVICE_NUM        INT          NOT NULL AUTO_INCREMENT COMMENT '장비 순번',
  OLD_DEVICE_ID     VARCHAR(20)  NULL     COMMENT '기존 장비 관리 번호',
  EMP_NUM           INT          NULL     COMMENT '사원 번호',
  ORG_ID            INT          NOT NULL COMMENT '조직 ID (기본키)',
  USAGE_DIVISION    VARCHAR(10)  NOT NULL COMMENT '용도구분(업무용,개발용,실증용)',
  USAGE_PURPOSE     VARCHAR(200) NOT NULL COMMENT '사용용도(개발업무용,내부망,외부망)',
  ARCHIVE_LOCATION  VARCHAR(200) NULL     COMMENT '사용/보관 위치',
  DEVICE_TYPE       VARCHAR(10)  NOT NULL COMMENT '장비 유형 코드',
  MANUFACTURER_CODE VARCHAR(10)  NULL     COMMENT '제조사 코드',
  MODEL_NAME        VARCHAR(100) NULL     COMMENT '모델명',
  MANUFACTURE_DATE  VARCHAR(8)   NULL     COMMENT '제조일자',
  CPU_SPEC          VARCHAR(100) NULL     COMMENT 'CPU 사양 (PC 전용)',
  MEMORY_SIZE       INT          NULL     COMMENT '메모리(GB, PC 전용)',
  STORAGE_INFO      VARCHAR(50)  NULL     COMMENT '스토리지 정보 (PC 전용)',
  OPERATING_SYSTEM  VARCHAR(100) NULL     COMMENT '운영체제',
  SCREEN_SIZE       DECIMAL(4,1) NULL     COMMENT '화면 크기 (PC/모니터 전용)',
  GPU_SPEC          VARCHAR(100) NULL     COMMENT 'GPU',
  STATUS_CODE       VARCHAR(10)  NULL     COMMENT '장비 상태 코드',
  PURCHASE_DATE     VARCHAR(8)   NULL     COMMENT '구매일자',
  RETURN_DATE       VARCHAR(8)   NULL     COMMENT '반납일자',
  REMARKS           TEXT         NULL     COMMENT '비고',
  CREATE_DATETIME   DATETIME     NULL     DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  CREATE_USER       INT          NOT NULL COMMENT '생성자',
  UPDATE_DATETIME   DATETIME     NULL     DEFAULT CURRENT_TIMESTAMP COMMENT '최종 변경일시',
  UPDATE_USER       INT          NULL     COMMENT '최종 변경자',
  PRIMARY KEY (DEVICE_NUM)
);

CREATE TABLE DEVICE_HISTORY
(
  HISTORY_NUM       INT          NOT NULL COMMENT '이력 순번',
  DEVICE_NUM        INT          NOT NULL COMMENT '장비 순번',
  OLD_DEVICE_ID     VARCHAR(20)  NULL     COMMENT '기존 장비 관리 번호',
  EMP_NUM           INT          NULL     COMMENT '사원 번호',
  ORG_ID            INT          NOT NULL COMMENT '조직 ID (기본키)',
  USAGE_DIVISION    VARCHAR(10)  NOT NULL COMMENT '용도구분(업무용,개발용,실증용)',
  USAGE_PURPOSE     VARCHAR(200) NOT NULL COMMENT '사용용도(개발업무용,내부망,외부망)',
  ARCHIVE_LOCATION  VARCHAR(200) NULL     COMMENT '사용/보관 위치',
  DEVICE_TYPE       VARCHAR(10)  NOT NULL COMMENT '장비 유형 코드',
  MANUFACTURER_CODE VARCHAR(10)  NULL     COMMENT '제조사 코드',
  MODEL_NAME        VARCHAR(100) NULL     COMMENT '모델명',
  MANUFACTURE_DATE  VARCHAR(8)   NULL     COMMENT '제조일자',
  CPU_SPEC          VARCHAR(100) NULL     COMMENT 'CPU 사양 (PC 전용)',
  MEMORY_SIZE       INT          NULL     COMMENT '메모리(GB, PC 전용)',
  STORAGE_INFO      VARCHAR(50)  NULL     COMMENT '스토리지 정보 (PC 전용)',
  OPERATING_SYSTEM  VARCHAR(100) NULL     COMMENT '운영체제',
  SCREEN_SIZE       DECIMAL(4,1) NULL     COMMENT '화면 크기 (PC/모니터 전용)',
  GPU_SPEC          VARCHAR(100) NULL     COMMENT 'GPU',
  STATUS_CODE       VARCHAR(10)  NULL     COMMENT '장비 상태 코드',
  PURCHASE_DATE     VARCHAR(8)   NULL     COMMENT '구매일자',
  RETURN_DATE       VARCHAR(8)   NULL     COMMENT '반납일자',
  REMARKS           TEXT         NULL     COMMENT '비고',
  CHANGE_REASON     TEXT         NULL     COMMENT '변경사유',
  CREATE_DATETIME   DATETIME     NULL     DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  CREATE_USER       INT          NOT NULL COMMENT '생성자',
  PRIMARY KEY (HISTORY_NUM)
);

CREATE TABLE DEVICE_TEMP
(
  DEVICE_NUM        INT          NOT NULL COMMENT '장비 순번',
  OLD_DEVICE_ID     VARCHAR(20)  NULL     COMMENT '기존 장비 관리 번호',
  EMP_NUM           INT          NULL     COMMENT '사원 번호',
  ORG_ID            INT          NOT NULL COMMENT '조직 ID (기본키)',
  USAGE_DIVISION    VARCHAR(10)  NOT NULL COMMENT '용도구분(업무용,개발용,실증용)',
  USAGE_PURPOSE     VARCHAR(200) NOT NULL COMMENT '사용용도(개발업무용,내부망,외부망)',
  ARCHIVE_LOCATION  VARCHAR(200) NULL     COMMENT '사용/보관 위치',
  DEVICE_TYPE       VARCHAR(10)  NOT NULL COMMENT '장비 유형 코드',
  MANUFACTURER_CODE VARCHAR(10)  NULL     COMMENT '제조사 코드',
  MODEL_NAME        VARCHAR(100) NULL     COMMENT '모델명',
  MANUFACTURE_DATE  VARCHAR(8)   NULL     COMMENT '제조일자',
  CPU_SPEC          VARCHAR(100) NULL     COMMENT 'CPU 사양 (PC 전용)',
  MEMORY_SIZE       INT          NULL     COMMENT '메모리(GB, PC 전용)',
  STORAGE_INFO      VARCHAR(50)  NULL     COMMENT '스토리지 정보 (PC 전용)',
  OPERATING_SYSTEM  VARCHAR(100) NULL     COMMENT '운영체제',
  SCREEN_SIZE       DECIMAL(4,1) NULL     COMMENT '화면 크기 (PC/모니터 전용)',
  GPU_SPEC          VARCHAR(100) NULL     COMMENT 'GPU',
  STATUS_CODE       VARCHAR(10)  NULL     COMMENT '장비 상태 코드',
  PURCHASE_DATE     VARCHAR(8)   NULL     COMMENT '구매일자',
  RETURN_DATE       VARCHAR(8)   NULL     COMMENT '반납일자',
  REMARKS           TEXT         NULL     COMMENT '비고',
  CHANGE_REASON     TEXT         NULL     COMMENT '변경사유'
);

CREATE TABLE NOTICE
(
  NOTICE_NUM      INT          NOT NULL AUTO_INCREMENT COMMENT '공지사항 번호',
  TITLE           VARCHAR(255) NOT NULL COMMENT '제목',
  CONTENT         TEXT         NOT NULL COMMENT '본문 내용',
  CREATE_DATETIME DATETIME     NULL     DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  CREATE_USER     INT          NOT NULL COMMENT '생성자',
  UPDATE_DATETIME DATETIME     NULL     DEFAULT CURRENT_TIMESTAMP COMMENT '최종 변경일시',
  UPDATE_USER     INT          NULL     COMMENT '최종 변경자',
  PRIMARY KEY (NOTICE_NUM)
);

CREATE TABLE ORGANIZATION
(
  ORG_ID          INT                                  NOT NULL COMMENT '조직 ID (기본키)',
  ORG_NAME        	VARCHAR(100)                       NOT NULL COMMENT '조직명',
  ORG_TYPE        ENUM('COMPANY', 'DIVISION', 'TEAM')  NOT NULL COMMENT '조직 유형 (COMPANY:회사, DIVISION:본부, TEAM:팀)',
  PARENT_ORG_ID   INT                                  NULL     DEFAULT 1 COMMENT '상위 조직 ID (자기 참조, 최상위는 NULL)',
  ORG_LEVEL       INT                                  NULL     COMMENT '조직 레벨 (1:회사, 2:본부, 3:팀)',
  ORG_PATH        VARCHAR(20)                          NULL     COMMENT '조직 경로 (1/2/3/4 형태로 계층 구조 표현)',
  SORT_ORDER      INT                                  NULL     DEFAULT 0 COMMENT '정렬 순서 (같은 레벨 내에서의 표시 순서)',
  IS_ACTIVE       CHAR(1)                              NULL     COMMENT '활성 여부 (Y:활성, N:비활성)',
  CREATE_DATETIME DATETIME                             NULL     DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ORG_ID)
) COMMENT '조직 정보 통합 테이블 (회사, 본부, 팀 계층 구조 관리)';

CREATE TABLE USER
(
  EMP_NUM              INT          NOT NULL COMMENT '사원 번호',
  USER_ID              VARCHAR(50)  NOT NULL COMMENT '사용자 ID (회사 메일 계정)',
  USER_NAME            VARCHAR(100) NOT NULL COMMENT '사용자명',
  PASSWORD             VARCHAR(100) NULL     DEFAULT 1111 COMMENT '비밀번호 (암호화 BCrypt)',
  ORG_ID               INT          NOT NULL COMMENT '조직 ID (기본키)',
  USER_POSITION_CD     VARCHAR(10)  NULL     COMMENT '직책 코드',
  USER_GRADE_CD        VARCHAR(10)  NOT NULL COMMENT '직위 코드',
  ROLE_CODE            VARCHAR(10)  NOT NULL COMMENT '권한 코드 (COMMON_CODE)',
  IS_EMPLOYED          CHAR(1)      NOT NULL DEFAULT 'Y' COMMENT '재직여부 (재직중:Y, 퇴사:N)',
  PASSWORD_CHANGE_DATE VARCHAR(8)   NULL     COMMENT '비밀번호 변경일자',
  CREATE_DATETIME      DATETIME     NULL     DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  PRIMARY KEY (EMP_NUM)
);